name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install
      - name: Lint (frontend)
        run: |
          cd frontend
          npm run lint || true
      - name: Test (frontend)
        run: |
          cd frontend
          npm test -- --watchAll=false || true
      - name: Install dependencies (backend)
        run: |
          cd backend
          npm install
      - name: Lint (backend)
        run: |
          cd backend
          npm run lint || true
      - name: Test (backend)
        run: |
          cd backend
          npm test || true